
path: D:\license-plate-yolov\data  # dataset root dir
train: data\platcola  # train images (relative to 'path')
val: data\platcola  # val images (relative to 'path')

# Classes
names:
  0: license_plate